//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCalculator.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalorieCalculator.API.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height in Feet.
        /// </summary>
        internal static string HeightFeet {
            get {
                return ResourceManager.GetString("HeightFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height in Inches.
        /// </summary>
        internal static string HeightInches {
            get {
                return ResourceManager.GetString("HeightInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter patient’s first name..
        /// </summary>
        internal static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height has to be equal to or greater than 5 feet!.
        /// </summary>
        internal static string InvalidHeight {
            get {
                return ResourceManager.GetString("InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter patient’s last name..
        /// </summary>
        internal static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Output.
        /// </summary>
        internal static string InvalidOutput {
            get {
                return ResourceManager.GetString("InvalidOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter valid SSN Part1..
        /// </summary>
        internal static string InvalidSSNPart1 {
            get {
                return ResourceManager.GetString("InvalidSSNPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter valid SSN Part2..
        /// </summary>
        internal static string InvalidSSNPart2 {
            get {
                return ResourceManager.GetString("InvalidSSNPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter valid SSN Part3..
        /// </summary>
        internal static string InvalidSSNPart3 {
            get {
                return ResourceManager.GetString("InvalidSSNPart3", resourceCulture);
            }
        }
    }
}
